name: Publish PyTest Report

on:
  workflow_run:
    workflows: ["pytest"]
    types: [completed]

permissions:
  contents: write

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pytest-html-report
          path: docs

      - name: Commit and push report
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/report.html
          git commit -m "Update pytest report" || echo "No changes"
          git push

          